[job]
dump_folder = "./outputs"
description = "Llama 3.2 1B training on MMLU dataset"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "1B"
norm_type = "rmsnorm"
tokenizer_path = "models/Llama3.2-1B-Instruct/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-5

[training]
batch_size = 4
seq_len = 2048
warmup_steps = 100
max_norm = 1.0
steps = 1000
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false
dataset_type = "custom"
dataset = "mmlu"
dataset_path = "torchtitan/datasets/mmlu"
loss_function = "classification"

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
load_step = 0
interval_type = "steps"
interval = 100
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"

[activation_checkpoint]
mode = 'selective'
selective_ac_option = 'op'

[float8]
enable_float8_linear = false