[job]
dump_folder = "./outputs"
description = "Llava one vision qwen2 7B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_wandb = true

[model]
name = "llava-hf/llava-onevision-qwen2-7b-ov-hf"
flavor = "7B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm

[optimizer]
name = "AdamW"
lr = 1e-5

[training]
batch_size = 1
seq_len = 65536 # 131072 # maximum sequence length for this model
warmup_steps = 1000  # lr scheduler warm up # warmup_ratio 0.03
max_norm = 1.0  # grad norm clipping
steps = 40000 # around 3 epochs
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = "alfred"
rope_type = "yarn"
rope_factor = 2.0

[experimental]
context_parallel_degree = 8
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 5000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
